/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-05-14 07:56:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>DB 연동 결과</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* 기본 배경 설정: 부드러운 그라데이션 */\r\n");
      out.write("    body { \r\n");
      out.write("        font-family: 'Pretendard', -apple-system, BlinkMacSystemFont, system-ui, Roboto, sans-serif; \r\n");
      out.write("        background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        height: 100vh;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 메인 카드 박스 */\r\n");
      out.write("    .container { \r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        padding: 40px; \r\n");
      out.write("        border-radius: 20px; \r\n");
      out.write("        box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 400px;\r\n");
      out.write("        transition: transform 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container:hover {\r\n");
      out.write("        transform: translateY(-5px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 제목 스타일 */\r\n");
      out.write("    h2 { \r\n");
      out.write("        color: #333; \r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        letter-spacing: -1px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 구분선 */\r\n");
      out.write("    hr {\r\n");
      out.write("        border: 0;\r\n");
      out.write("        height: 1px;\r\n");
      out.write("        background: #eee;\r\n");
      out.write("        margin: 20px 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 결과 텍스트 영역 */\r\n");
      out.write("    .result-box {\r\n");
      out.write("        background-color: #f8f9fa;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("        border-left: 5px solid #007bff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .result-label {\r\n");
      out.write("        display: block;\r\n");
      out.write("        font-size: 0.85rem;\r\n");
      out.write("        color: #6c757d;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .result-content {\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("        color: #212529;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        word-break: break-all;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 버튼 스타일 */\r\n");
      out.write("    button { \r\n");
      out.write("        background-color: #007bff; \r\n");
      out.write("        color: white; \r\n");
      out.write("        border: none; \r\n");
      out.write("        padding: 12px 25px; \r\n");
      out.write("        border-radius: 8px; \r\n");
      out.write("        cursor: pointer; \r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    button:hover { \r\n");
      out.write("        background-color: #0056b3; \r\n");
      out.write("        box-shadow: 0 4px 12px rgba(0, 123, 255, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    button:active {\r\n");
      out.write("        transform: scale(0.98);\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2>📊 데이터 조회 결과</h2>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div class=\"result-box\">\r\n");
      out.write("            <span class=\"result-label\">조회 내용</span>\r\n");
      out.write("            <p class=\"result-content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button onclick=\"history.back()\">이전 화면으로</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
