# MySQL \uB4DC\uB77C\uC774\uBC84
db.driverClass=com.mysql.cj.jdbc.Driver
# DB URL
db.url=jdbc:mysql://my8003.gabiadb.com:3306/hkcodedb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
# \uACC4\uC815 \uC815\uBCF4
db.username=hkcode
db.password=fintech1308!
